#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
<<<<<<< Updated upstream
# Generated by Vivado on Fri Dec 15 12:19:05 EST 2023
=======
# Generated by Vivado on Fri Dec 15 17:12:02 EST 2023
>>>>>>> Stashed changes
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_RV32I_behav -key {Behavioral:sim_1:Functional:tb_RV32I} -tclbatch tb_RV32I.tcl -log simulate.log"
xsim tb_RV32I_behav -key {Behavioral:sim_1:Functional:tb_RV32I} -tclbatch tb_RV32I.tcl -log simulate.log

