set_property SRC_FILE_INFO {cfile:C:/Users/User/RISC-V_Local/RISC-V_Local.srcs/constrs_1/imports/XDC/Basys3_Master.xdc rfile:../../../../../RISC-V_Local.srcs/constrs_1/imports/XDC/Basys3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]
